;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        LaTeX-babel-insert-hyphen
        TeX-insert-sub-or-superscript
        end-of-visual-line
        mouse-set-secondary
        org-beginning-of-line
        org-delete-char
        org-force-self-insert
        org-self-insert-command
        org-yank
        reindent-then-newline-and-indent
        sgml-close-tag
        undo-tree-visualize
        ))

(setq mc/cmds-to-run-once
      '(
        LaTeX-insert-item
        LaTeX-insert-left-brace
        TeX-command-master
        TeX-insert-backslash
        TeX-next-error
        TeX-view
        backward-page
        cdlatex-pbb
        keyboard-escape-quit
        mac-mwheel-scroll
        mouse-minor-mode-menu
        mouse-save-then-kill
        mouse-set-region
        mouse-start-secondary
        org-ctrl-c-ctrl-c
        org-meta-return
        org-metaleft
        org-metaright
        org-preview-latex-fragment
        org-sparse-tree
        reftex-citation
        switch-to-buffer
        ))
